name=LCDFlasher
version=1.0.1
author=Michael Mulvey
maintainer=Michael Mulvey <michael.e.mulvey@gmail.com>
sentence=Custom LCD text effects like flashing messages for I2C 20x4 displays.
paragraph=A lightweight library to provide flashing and clearing text effects using LiquidCrystal_I2C on 20x4 I2C displays.
category=Display 
url=https://github.com/Z1ll1Quister/LDCFlasher
architectures=*
